# MK Praktikum Unggulan Universitas Gunadarma
# Mata Kuliah: Praktikum Teknologi Kecerdasan Artifisial (Tingkat 1)

---
# Pertemuan II - Python Matriks dan NumPy Array

Matriks adalah struktur data dua dimensi dimana angka-angka disusun menjadi baris dan kolom. Contohnya:

<img src="https://cdn.programiz.com/sites/tutorial2program/files/matrix.jpg">

Matriks ini adalah matriks 3x4 (dibaca "tiga kali empat") karena memiliki 3 baris dan 4 kolom.

### Python Matriks
Python tidak memiliki tipe built-in untuk matriks. Namun, list di dalam list dapat digunakan untuk merepresentasikan matriks. Contohnya sebagai berikut:

In [1]:
A = [[1, 4, 5],
    [-5, 8, 9]]

Kita dapat memperlakukan list ini sebagai matriks yang memiliki 2 baris dan 3 kolom.

<img src="https://cdn.programiz.com/sites/tutorial2program/files/matrix-python-example.jpg">

**Contoh Kode Program**

In [2]:
A = [[1, 4, 5, 12],
    [-5, 8, 9, 0],
    [-6, 7, 11, 19]]

Untuk mencetak atau mendapatkan seluruh nilai yang ada pada matriks di atas dapat digunakan perintah:

In [3]:
print("A =", A)

A = [[1, 4, 5, 12], [-5, 8, 9, 0], [-6, 7, 11, 19]]


Selain itu, untuk mendapatkan elemen tertentu dari matriks tersebut dapat dilakukan dengan cara:

In [4]:
# Mengakses seluruh elemen pada baris ke-2 (index dimulai dari 0)
print("A[1] =", A[1])

# Mengakses elemen ke-3 dari baris ke-2 (baris index 1, kolom index 2)
print("A[1][2] =", A[1][2])

# Mengakses elemen terakhir dari baris ke-1
# (-1 berarti index terakhir dalam Python)
print("A[0][-1] =", A[0][-1])

A[1] = [-5, 8, 9, 0]
A[1][2] = 9
A[0][-1] = 12


---
### NumPy Array
NumPy adalah library Python yang digunakan untuk komputasi ilmiah. Library ini menyediakan dukungan untuk objek array berdimensi-N (multidimensi).
<br><br>
Contoh:

In [ ]:
import numpy as np

a = [1, 2, 3])

print(a)

print(type(a))

[1 2 3]
<class 'numpy.ndarray'>


Seperti yang Anda lihat, kelas array NumPy disebut `ndarray`.

<br>

### Bagaimana cara membuat array NumPy?
Ada beberapa cara untuk membuat array NumPy.

1. Array bilangan bulat, float dan bilangan kompleks.

In [ ]:
# Membuat array 2 dimensi (2 baris, 3 kolom) berisi bilangan bulat
A = [[1, 2, 3], [3, 4, 5]])
print(A)

[[1 2 3]
 [3 4 5]]


In [8]:
# Membuat array 2 dimensi (2 baris, 3 kolom) berisi bilangan float (desimal)
A = np.array([[1.1, 2, 3], [3, 4, 5]])
print(A)

[[1.1 2.  3. ]
 [3.  4.  5. ]]


In [9]:
# Membuat array 2 dimensi (2 baris, 3 kolom) berisi bilangan kompleks
A = np.array([[1, 2, 3], [3, 4, 5]], dtype=complex)
print(A)

[[1.+0.j 2.+0.j 3.+0.j]
 [3.+0.j 4.+0.j 5.+0.j]]


2. Array angka nol dan satu

In [10]:
zeroes_array = np.zeros( (2, 3) )
print(zeroes_array)

[[0. 0. 0.]
 [0. 0. 0.]]


Selain itu, kita juga dapat menetapkan `dtype` menjadi 32 bit (4 byte). Karena array ini dapat mengambil nilai dari <code>-2<sup>-31</sup></code> hingga <code>2<sup>-31</sup>-1</code>.

In [11]:
ones_array = np.ones( (1, 5), dtype=np.int32 ) # menentukan dtype
print(ones_array)

[[1 1 1 1 1]]


---

### Operasi Matriks

Pada contoh program selanjutnya akan dibuat 3 jenis program yaitu:
1. Penjumlahan dua buah matriks,
2. Perkalian dua buah matriks dan
3. Transpos sebuah matriks.

Jika menggunakan program python biasa, kita memerlukan `nested lists` untuk membuat program tersebut. Namun ada cara yang lebih baik yaitu menggunakan library NumPy.

#### **Penambahan Dua Matriks**

Kita dapat menggunakan operator `+` untuk menambahkan elemen yang sesuai dari dua matriks NumPy.

In [12]:
A = np.array(
    [[3, 4],
     [2, 1]])

B = np.array(
    [[1, 5],
     [3, 7]])

C = A + B

print(C)

[[4 9]
 [5 8]]


#### **Perkalian Dua Matriks**

Untuk mengalikan dua matriks, kita menggunakan metode `dot()`.

**Catatan**: `*` digunakan untuk perkalian array (perkalian elemen yang sesuai dari dua array) bukan perkalian matriks.

In [ ]:
A = np.array(
    [[3, 4],
     [2, 1]])

B = np.array(
    [[1, 5],
     [3, 7]])

C = A.dot(B)

print(C)

---
#### **Transpose Matriks**

Kita dapat menggunakan `numpy.transpose` untuk menghitung transpose matriks.

In [24]:
A = np.array(
    [[3, 4],
     [2, 1]])

print(A.transpose())

[[3 2]
 [4 1]]


---

## **Tugas**

Pada contoh program diatas, telah dibuat tiga program menggunakan library NumPy, yaitu:
1. Penjumlahan dua matriks
2. Perkalian dua matriks
3. Transpose matriks

Tugas Anda adalah membuat kembali ketiga program tersebut (nilai bebas) **tanpa menggunakan library NumPy**, melainkan menggunakan struktur data dasar Python (seperti list) dan perulangan.

In [ ]:
# 1. Penjumlahan dua matriks
# CODE HERE ...
a =[[6,7,4],[1,2,3]]
b =[[5,8,2],[7,6,5]]

print ("A =", a)
print ("B =", b)

hasil = []
for i in range(len(a)):
    baris = []
    for j in range(len(a[i])):
        baris.append(a[i][j] + b[i][j])
    hasil.append(baris)
    
print ("\nHasil A + B =",hasil)


A = [[6, 7, 4], [1, 2, 3]]
B = [[5, 8, 2], [7, 6, 5]]

 Hasil A + B = [[11, 15, 6], [8, 8, 8]]


In [ ]:
# 2. Perkalian dua matriks
# CODE HERE ...
a = [[6,7,4],[1,2,3]]
b = [[5,8,2],[7,6,5]]

print ("A =", a)
print ("B =", b)

hasil = []
for i in range(len(a)):
    baris = []
    for j in range(len(a[i])):
        baris.append(a[i][j] * b[i][j])
        
    hasil.append(baris)
    
print ("\nHasil A * B =",hasil)


A = [[6, 7, 4], [1, 2, 3]]
B = [[5, 8, 2], [7, 6, 5]]

Hasil A * B = [[30, 56, 8], [7, 12, 15]]


In [ ]:
# 3. Transpose matriks
# CODE HERE ...
a = [[6,7,4],[1,2,3]]
b = [[5,8,2],[7,6,5]]

print ("A =", a)
print ("B =", b)

def transpose(matrix):
    hasil = []
    for i in range(len(matrix[0])):
        baris = []
        for j in range(len(matrix)):
            baris.append(matrix[j][i])
        hasil.append(baris)
    return hasil

print (
f"""
Transpose A = {transpose(a)}
Transpose B = {transpose(b)}
""")



A = [[6, 7, 4], [1, 2, 3]]
B = [[5, 8, 2], [7, 6, 5]]

Transpose A = [[6, 1], [7, 2], [4, 3]]
Transpose B = [[5, 7], [8, 6], [2, 5]]



<div class="alert alert-warning">
<strong>Perhatian!</strong> Berikut merupakan cara konversi File IPYNB menjadi File PDF untuk melakukan pengumpulan tugas di Virtual Class.
    <a href="https://youtu.be/qXELXtnAK7c">Video konversi</a>.
    </div>



---


Copyright © Pengelola MK Praktikum Unggulan (Praktikum DGX), Universitas Gunadarma


https://www.praktikum-hpc.gunadarma.ac.id/